ecomsite/ecomsite/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
from users import views as UserViews
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),

    #Shop App Url's
    path('', views.HomePage,name='index'),
    path('DetailView/<id>', 
        views.DetailView,
        name='DetailView'),
    path('Addtocart/<id>', 
        views.Addtocart,
        name='Addtocart'),
    path('searchfunction/<title>', 
        views.searchfunction,
        name='searchfunction'),
    path('Pagination/<objectset>', 
        views.Pagination,
        name='Pagination'),
    path('cartcount', 
        views.cartcount,
        name='cartcount'),
    path('SubCatergory_View/<id>', 
        views.SubCatergory_View,
        name='SubCatergory_View'),
    path('Products_View/<id>', 
        views.Products_View,
        name='Products_View'),
    path('Sortingfunc/<id>', 
        views.Sortingfunc,
        name='Sortingfunc'),
    path('Increment_cart_quantity/<id>', 
        views.Increment_cart_quantity,
        name='Increment_cart_quantity'),
    path('Ordersummary', 
        views.Ordersummary,
        name='Ordersummary'),
    path('remove_single_item_from_cart/<id>', 
        views.remove_single_item_from_cart,
        name='remove_single_item_from_cart'
        ),
    path('RemoveFromcart/<id>', 
        views.RemoveFromcart,
        name='RemoveFromcart'
        ),
    path('checkout', 
        views.checkout,
        name='checkout'),


    #Users App Url's
    path('Registration/', 
        UserViews.Registration,
        name='Registration'),
    path('Profile/', 
        UserViews.Profile,
        name='Profile'),
    path('Login/', 
        auth_views.LoginView.as_view(template_name='users/Login.html'),
        name='Login'),
    path('Logout/', 
        auth_views.LogoutView.as_view(template_name='users/Logout.html'),
        name='Logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomsite/shop/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Maincategories(models.Model):
	MainCategory = models.CharField(max_length=200)
	MainCategory_image = models.ImageField(upload_to='category/',default='category/default.jpg')

	def __str__(self):
		return self.MainCategory

class Subcategories(models.Model):
	MainCategory = models.ForeignKey(Maincategories,on_delete=models.CASCADE)
	SubCategory = models.CharField(max_length=200)
	SubCategory_image = models.ImageField(upload_to='subcategory/',default='subcategory/default.jpg')

	def __str__(self):
		return self.SubCategory

class Products(models.Model):
	title = models.CharField(max_length=200)
	SubCategory = models.ForeignKey(Subcategories,on_delete=models.CASCADE,blank=True,null=True)
	image = models.ImageField(upload_to='Products/',default='/Products/default.jpg')
	description = models.TextField()
	price = models.FloatField()
	discount_price = models.FloatField(blank=True,null=True)

	def __str__(self):
		return self.title

class OrderItem(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		blank=True,
		null=True)
	item = models.ForeignKey(Products,on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	ordered = models.BooleanField(default=False) 

	def __str__(self):
		return f"{self.quantity} of {self.item.title}"

	def get_total_item_price(self):
		return self.quantity * self.item.price

	def get_total_discount_item_price(self):
		return self.quantity * self.item.discount_price

	def get_amount_saved(self):
		return self.get_total_item_price() - self.get_total_discount_item_price()

	def get_final_price(self):
		if self.item.discount_price:
			 return self.get_total_discount_item_price()
		return self.get_total_item_price()


class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		blank=True,
		null=True)
	items = models.ManyToManyField(OrderItem)
	start_date = models.DateTimeField(auto_now_add=True)
	ordered_date = models.DateTimeField()
	ordered = models.BooleanField(default=False)
	billing_address = models.ForeignKey('Billing_Address',on_delete=models.SET_NULL,blank=True,
		null=True)

	def __str__(self):
		return self.user.username

	def get_total(self):
		total = 0 
		for order_item in self.items.all():
			total += order_item.get_final_price()
		# if self.coupon:
		# 	total -= self.coupon.amount
		return total

class Billing_Address(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	address = models.CharField(max_length=1000)
	landmark = models.CharField(max_length=300)
	city = models.CharField(max_length=300)
	country = models.CharField(max_length=200)
	zipcode = models.CharField(max_length=200)

	def __str__(self):
		return self.user.username

ecomsite/shop/forms.py
from django import forms
from .models import Billing_Address

class CheckoutForm(forms.ModelForm):
	class Meta():
		model = Billing_Address
		fields = ('address','landmark','city','country','zipcode')

		widgets={
			'address' : forms.TextInput(attrs={'placeholder':'address'}),
			'landmark' : forms.TextInput(attrs={'placeholder':'landmark'}),
			'city' : forms.TextInput(attrs={'placeholder':'city'}),
			'country' : forms.TextInput(attrs={'placeholder':'country'}),
			'zipcode' : forms.TextInput(attrs={'placeholder':'zipcode'})
		}

ecomsite/shop/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from .models import (Products,
	OrderItem,
	Order,
	Billing_Address,
	Maincategories,
	Subcategories)
from django.core.paginator import Paginator
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CheckoutForm
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def HomePage(request):  
	Listofmains = extra(request)   
	order_obj = cartcount(request)
	product_objects = Maincategories.objects.all()

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		context ={
			'product_objects' : product_objects,
			'order_obj' : order_obj,
			'Listofmains' : Listofmains
		}
		return render(request,'shop/SearchPage.html',context=context)

	product_objects = Pagination(request,objectset=product_objects)
	
	#other Logic
	context ={
		'product_objects' : product_objects,
		'order_obj' : order_obj,
		'Listofmains' : Listofmains
	}
	return render(request,'shop/HomePage.html',context=context)

def SubCatergory_View(request,id):
	Listofmains = extra(request)     
	order_obj = cartcount(request)
	Subcategories_obj = Subcategories.objects.filter(MainCategory=id)
	Subcategories_obj = Pagination(request,objectset=Subcategories_obj)

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		context ={
			'product_objects' : product_objects,
			'order_obj' : order_obj,
			'Listofmains' : Listofmains
		}
		return render(request,'shop/SearchPage.html',context=context)

	context ={
		'order_obj' : order_obj,
		'Listofmains' : Listofmains,
		'Subcategories_obj' : Subcategories_obj
	}
	return render(request,'shop/SubCatergory.html',context=context)

def Products_View(request,id):
	Listofmains = extra(request)  
	order_obj = cartcount(request)
	Products_obj = Products.objects.filter(SubCategory=id)
	Products_obj = Pagination(request,objectset=Products_obj)

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		context ={
			'product_objects' : product_objects,
			'order_obj' : order_obj,
			'Listofmains' : Listofmains
		}
		return render(request,'shop/SearchPage.html',context=context)
		
	context={
		'order_obj':order_obj,
		'subcat_id': id,
		'Products_obj' : Products_obj,
		'Listofmains' : Listofmains
			}
	return render(request,'shop/Products.html',context=context)

def Sortingfunc(request,id):
	Listofmains = extra(request)  
	order_obj = cartcount(request)
	Products_obj = Products.objects.filter(SubCategory=id).order_by('discount_price')
	Products_obj = Pagination(request,objectset=Products_obj)

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		context ={
			'product_objects' : product_objects,
			'order_obj' : order_obj,
			'Listofmains' : Listofmains
		}
		return render(request,'shop/SearchPage.html',context=context)
		
	context={
		'order_obj' : order_obj,
		'subcat_id': id,
		'Products_obj' : Products_obj,
		'Listofmains' : Listofmains
			}
	return render(request,'shop/Products.html',context=context)

def DetailView(request,id):
	Listofmains = extra(request) 
	order_obj = cartcount(request) 
	product_object = Products.objects.get(id=id)

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		context ={
			'product_objects' : product_objects,
			'order_obj' : order_obj,
			'Listofmains' : Listofmains
		}
		return render(request,'shop/SearchPage.html',context=context)
		
	#other Logic
	context ={
		'product_object' : product_object,
		'order_obj' : order_obj,
		'Listofmains' : Listofmains
	}
	return render(request,'shop/Itemdetail.html',context=context)

@login_required
def Addtocart(request,id):
	item = get_object_or_404(Products,id=id)
	order_item,created = OrderItem.objects.get_or_create(
		item=item,
		user=request.user,
		ordered=False
		)
	order_qs = Order.objects.filter(user=request.user,ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		#check order item in order
		if order.items.filter(item__id=item.id).exists():
			order_item.quantity += 1
			order_item.save()
		else:
			order.items.add(order_item)
	else:
		ordered_date = timezone.now()
		order = Order.objects.create(
			user = request.user,
			ordered_date = ordered_date)
		order.items.add(order_item)
	messages.success(request,f"Item has been added to cart!")
	return redirect('DetailView', id=id)

@login_required
def Ordersummary(request):
	Listofmains = extra(request)  
	try:
		order_obj = Order.objects.get(user=request.user,ordered=False)
	except ObjectDoesNotExist:
		order_obj = None

	#Search code
	item_name = request.POST.get('item_name')
	if item_name != '' and item_name is not None:
		product_objects=searchfunction(request,title=item_name)
		product_objects = Pagination(request,objectset=product_objects)
		return render(request,'shop/SearchPage.html',{'product_objects' : product_objects})
	
	context={
		'order_obj' : order_obj,
		'Listofmains' : Listofmains
	}
	return render(request,'shop/ordersummary.html',context=context)

@login_required
def Increment_cart_quantity(request,id):
	item = get_object_or_404(Products,id=id)
	order_item,created = OrderItem.objects.get_or_create(
		item=item,
		user=request.user,
		ordered=False
		)
	order_qs = Order.objects.filter(user=request.user,ordered=False)
	if order_qs.exists():
		order = order_qs[0]
		#check order item in order
		if order.items.filter(item__id=item.id).exists():
			order_item.quantity += 1
			order_item.save()
		else:
			order.items.add(order_item)
	else:
		ordered_date = timezone.now()
		order = Order.objects.create(
			user = request.user,
			ordered_date = ordered_date)
		order.items.add(order_item)
	return redirect('Ordersummary')

@login_required
def remove_single_item_from_cart(request, id):
    item = get_object_or_404(Products, id=id)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("Ordersummary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("Ordersummary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("Ordersummary")

@login_required
def RemoveFromcart(request, id):
    item = get_object_or_404(Products, id=id)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, "This item quantity was updated.")
            return redirect("Ordersummary")
        else:
            messages.info(request, "This item was not in your cart")
            return redirect("Ordersummary")
    else:
        messages.info(request, "You do not have an active order")
        return redirect("Ordersummary")

@login_required
def checkout(request):
	if request.method == 'POST':
		order_obj = Order.objects.get(user=request.user,ordered=False)
		user = request.user
		address = request.POST.get('address',"")
		landmark = request.POST.get('landmark',"")
		city = request.POST.get('city',"")
		country = request.POST.get('country',"")
		zipcode = request.POST.get('zipcode',"")
		billing = Billing_Address(user=user,
			address=address,
			landmark=landmark,
			city=city,
			country=country,
			zipcode=zipcode)
		billing.save()
		order_obj.billing_address = billing
		order_obj.save()
		messages.success(request,"Your order has been placed successfully !")
		return redirect('index')
	return render(request,'shop/checkout.html')

#Extra Functions
def searchfunction(request,title):
	product_objects = Products.objects.filter(title__icontains=title)
	return product_objects

def Pagination(request,objectset):
	paginator = Paginator(objectset,9)
	page = request.GET.get('page')
	product_objects = paginator.get_page(page)
	return product_objects

def cartcount(request):
	if request.user.is_authenticated:
		try:
			order_obj = Order.objects.get(user=request.user,ordered=False)
		except ObjectDoesNotExist:
			order_obj =0
	else:
		order_obj = None
	return order_obj

def extra(request):
	maincats = Maincategories.objects.all()
	olddict ={}
	for i in maincats:
		olddict[i] = Subcategories.objects.filter(MainCategory=i.id)
	return olddict

ecomsite/shop/templates/shop/HomePage.html
{% extends 'shop/BasePage.html' %}
{% load static %}
{% block content %}
<!-- main-slider -->
<ul id="demo1">
	<li>
		<img src="{% static 'shop/images/11.jpg' %}" alt="" />
		<div class="slide-desc">
			<h3>Buy Latest Products Are Now On Line With Us</h3>
		</div>
	</li>
	<li>
		<img src="{% static 'shop/images/22.jpg' %}" alt="" />
		  <div class="slide-desc">
			<h3>Whole Brand New Products Are Now On Line With Us</h3>
		</div>
	</li>
	<li>
		<img src="{% static 'shop/images/44.jpg' %}" alt="" />
		<div class="slide-desc">
			<h3>Whole Products Are Now On Line With Us</h3>
		</div>
	</li>
</ul>
<!-- //main-slider -->
<div class="top-brands">
	<div class="container">
		<h2>Top selling offers</h2>
			<div class="grid_3 grid_5">
				<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					<div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="expeditions" aria-labelledby="expeditions-tab">
						<div class="agile_top_brands_grids">
							{% for product in product_objects %}
							<div class="col-md-4 top_brand_left">
								<div class="hover14 column">
									<div class="agile_top_brand_left_grid">
						<div class="agile_top_brand_left_grid_pos">
							<img src="{% static 'shop/images/offer.png' %}"  alt=" " class="img-responsive" />
						</div>
						<div class="agile_top_brand_left_grid1">
							<figure>
								<div class="snipcart-item block" >
		<div class="snipcart-thumb">
			<a href="{% url 'SubCatergory_View' id=product.id %}"><img title=" " alt=" " src="{{product.MainCategory_image.url}}" width='250px' height='auto'/></a>		
			<p><strong>{{product.MainCategory}}</strong></p>
			<!-- <h4>${{product.price}}<span>${{product.discount_price}}</span></h4> -->
		</div>
		<div class="snipcart-details top_brand_home_details">
			<!-- <a href="{% url 'DetailView' id=product.id %}">
				<input type="submit" name="submit" value="Quick View" class="button" />
			</a> -->
			<a href="{% url 'SubCatergory_View' id=product.id %}">
				<input type="submit" name="submit" value="Quick View" class="button" />
			</a>
		</div>
								</div>
							</figure>
						</div>
					</div>
				</div>
			</div>
		{% endfor %}
<!--PAGINATION CODE---------->
<!-- <div class="row">
	<div class='col-md-3 offset-md-4'>
		<ul class='pagination'>
			{% if product_objects.has_previous %}
				<li class='page-item'>
					<a class='page-link' href="?page={{ product_objects.previous_page_number }}">Previous</a>
				</li>
			{% endif %}
				<li class='page-item active'>
					<a class='page-link' href="?page={{ product_objects.number }}">Current</a>
				</li>
			{% if product_objects.has_next %}
				<li class='page-item'>
					<a class='page-link' href="?page={{ product_objects.next_page_number }}">Next</a>
				</li>
			{% endif %}
		</ul>
	</div>
</div> -->

<!--PAGINATION CODE---------->
<div class="clearfix"></div>
<!--PAGINATION CODE---------->
<nav class="numbering">
	<ul class="pagination paging">
		{% if Subcategories_obj.has_previous %}
			<li>
				<a href="?page={{ Subcategories_obj.previous_page_number }}">Previous</a>
			</li>
		{% endif %}
			<li class="active">
				<a href="?page={{ Subcategories_obj.number }}">current<span class="sr-only">(current)</span>
				</a>
			</li>
		{% if Subcategories_obj.has_next %}
			<li><a href="?page={{ Subcategories_obj.next_page_number }}">Next</a></li>
		{% endif %}
	</ul>
</nav>
<!--PAGINATION CODE---------->
</div>
</div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

ecomsite/shop/templates/shop/Itemdetail.html
{% extends 'shop/BasePage.html' %}
{% load static %}
{% block content %}
<!-- breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
			<li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
			<li class="active">{{ product_object.title }}</li>
		</ol>
	</div>
</div>
<!-- //breadcrumbs -->
<div class="products">
	<div class="container">
		<div class="agileinfo_single">
			<div class="col-md-4 agileinfo_single_left">
				<img id="example" src="{{ product_object.image.url }}" alt=" " class="img-responsive">
			</div>
			<div class="col-md-8 agileinfo_single_right">
			<h2>{{ product_object.title }}</h2>
				<div class="w3agile_description">
					<h4>Description :</h4>
					<p>{{ product_object.description }}</p>
				</div>
				<div class="snipcart-item block">
					<div class="snipcart-thumb agileinfo_single_right_snipcart">
					{% if product_object.discount_price %}	
						<h4 class="m-sing"><img width='9px' src='{% static "shop/rupee.png" %}'>{{ product_object.discount_price }} <span><img width='9px' src='{% static "shop/rupee.png" %}'>{{ product_object.price }}</span></h4>
					{% else %}	
						<h4 class="m-sing"><img width='9px' src='{% static "shop/rupee.png" %}'>{{ product_object.price }}</span></h4>
					{% endif %}
					</div>
				{% if user.is_authenticated %}
					<div class="snipcart-details agileinfo_single_right_details">
						<a href="{% url 'Addtocart' id=product_object.id %}">
							<input type="submit" name="submit" value="Add to cart" class="button">
						</a>
					</div>
				{% else %}
					<div class="snipcart-details agileinfo_single_right_details">
						<a href="{% url 'Login' %}">
							<input type="submit" name="submit" value="Add to cart" class="button">
						</a>
					</div>
				{% endif %}
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>  	
{% endblock %}

ecomsite/shop/templates/shop/checkout.html
{% extends 'shop/BasePage.html' %}
{% block content %}
{% load crispy_forms_tags %}
<!-- breadcrumbs -->
  <div class="breadcrumbs">
    <div class="container">
      <ol class="breadcrumb breadcrumb1">
        <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
        <li class="active">Checkout Page</li>
      </ol>
    </div>
  </div>
<!-- //breadcrumbs -->
<!-- checkout form -->
<div class="register">
    <div class="container">
        <h2>Enter shipping details</h2>
        <div class="login-form-grids">
            <form method="post">
                {% csrf_token %}
                <div id="div_id_address" class="form-group"> 
                  <!-- <label for="id_address" class=" requiredField">
                Address<span class="asteriskField">*</span> </label>--> 
                  <div class=""> 
                    <input type="text" name="address" maxlength="1000" class="textinput textInput form-control" placeholder='Enter Your Address' required id="id_address"> 
                  </div> 
                </div> 
                <div id="div_id_landmark" class="form-group"> 
                 <!--  <label for="id_landmark" class=" requiredField">
                Landmark<span class="asteriskField">*</span> </label>  -->
                  <div class="">  
                   <input type="text" name="landmark" maxlength="300" class="textinput textInput form-control" placeholder='Enter Your Landmark' required id="id_landmark"> 
                  </div> 
                </div>
                <div id="div_id_city" class="form-group"> 
                <!-- <label for="id_city" class=" requiredField">
                City<span class="asteriskField">*</span> </label> --> 
                  <div class=""> 
                    <input type="text" name="city" maxlength="300" placeholder='Enter Your Landmark' class="textinput textInput form-control" required id="id_city"> 
                  </div> 
                </div> 
                <div id="div_id_country" class="form-group"> 
                <!-- <label for="id_country" class=" requiredField">
                Country<span class="asteriskField">*</span> </label> --> 
                  <div class=""> 
                    <input type="text" name="country" maxlength="200" placeholder='Enter Your Country' class="textinput textInput form-control" required id="id_country"> 
                  </div> 
                </div> 
                <div id="div_id_zipcode" class="form-group"> 
                <!-- <label for="id_zipcode" class=" requiredField">
                Zipcode<span class="asteriskField">*</span> </label> --> 
                  <div class=""> 
                    <input type="text" name="zipcode" maxlength="200" placeholder='Enter Your Zipcode' class="textinput textInput form-control" required id="id_zipcode"> 
                  </div> 
                </div>
                <input type="submit" value="Proceed to Payment">
            </form>
        </div>
    </div>
</div>
<!-- checkout form -->
    <!-- <div class="row m-5">
      <div class="col-md-12">
        <h1>Enter shipping details</h1>
        <hr>
      </div>
    </div> -->
  <!--   <div class="row m-5">
      <div class="col-md-12">
          <form method="POST" >
            {% csrf_token %}
                <input type="hidden" id="items" name="items">
              <div class="form-row">
              </div>
              <div class="form-group">
                <label for="inputAddress">Address</label>
                <input id="address" name="address" type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="inputCity">Landmark</label>
                  <input id="city" name="city" type="text" class="form-control" id="inputCity">
                </div>
                <div class="form-group col-md-4">
                  <label for="inputState">State</label>
                  <input id="state" name="state" type="text" class="form-control" id="inputCity">
                </div>
                <div class="form-group col-md-2">
                  <label for="inputZip">Zip</label>
                  <input id="zipcode" name="zipcode" type="text" class="form-control" id="inputZip">
                </div>
                <div class="form-group col-md-2">
                  <label for="inputZip">Amount to be paid</label>
                  <input readonly="" type="text" class="form-control" id="total" name="total">
                </div>
              </div>
              <button type="submit" class="btn btn-warning">Place Order</button>
            </form>
      </div>
    </div> -->
{% endblock %}